### ISSUE TITLE
Accessibility support?

### ISSUE THREAD

**Issue by rcarmo** [nate-parrott/Flashlight#100]
This is more of a question than a bug - I've been trying to duplicate my favourite Quicksilver feature, which is to search (and trigger) the menus of the current application. I can sort of do it outside Flashlight using PyObjC in a standalone script, but my stub doesn't seem to work inside Flashlight, and I was wondering if something else is required on Flashlight (dropping the app into the Security / Accessibility pane doesn't seem to improve matters).

**Comment by nate-parrott** [comment]
I built a [Search Menu Items](http://flashlight.nateparrott.com/plugin/click-menu) plugin recently — it works alright. It uses applescript, although `pyatom` could probably give a substantial speed boost, if I could get it working in a plugin environment.
