### ISSUE TITLE
Add latest version of flashlight download link for homebrew-cask

### ISSUE THREAD

**Issue by jsfaint** [nate-parrott/Flashlight#104]
I'm not sure if anyone else also use hombrew-cask. :)
homebrew-cask is an external command for homebrew, which is provide management of OS X App via command line.

Due to Flashlight have build-in update mechanism, but there is no latest download link for it, so the cask script need to update version by version. 

There is no need to update the cask script If the latest version of flashlight download link was provided for it.Anyone who install flashlight via homebrew-cask will always get the latest version.

Sorry for my bad English, I'm not sure if I describe it clearly.

**Comment by vitorgalvao** [comment]
Thank you for keeping this link @nate-parrott, but we’re now changing a bit how we do things in homebrew-cask, so we’ll no longer be needing the link, in case you want to stop maintaining it.

Thank you again.
