### ISSUE TITLE
Separate all web search plugins

### ISSUE THREAD

**Issue by lipe1966** [nate-parrott/Flashlight#146]
I want to share my opinion with you guys and get what do you think about it. 
the web search plugin and other plugins that search the web should be separated in individual plugins for each search engine. 

1 - would be easy to adapt each plugin to the type of search and special commands each one of the engines might have.
2 - in case of conflict or problem with the plugin would be easier to identify the problem without going thru all the search engines.
3 - is cleaner 
4 - give each user the ability to choose what web search it wants.

**Comment by xremix** [comment]
@lipe1966 @nate-parrott I'd rethink this issue now, as we have settings. What do you think? Would it make sense to combine them again and make a setting where the user can select which sites should be searched?
