### ISSUE TITLE
Selection text color

### ISSUE THREAD

**Issue by jcavar** [nate-parrott/Flashlight#198]
![screen shot 2014-12-15 at 15 03 32](https://cloud.githubusercontent.com/assets/3751289/5436911/cb9f107c-846b-11e4-80df-a5a1677f0250.png)

If you select plugin in a list it is not looking good. I thought that this is easy task, but it seems that there is some work to do to fix this. I think that reason for this is that current architecture violates MVC. Here is what i think about it:
*   `PluginModel` shouldn't have `attributedString` mehtod. This should belong to `PluginCellView` because this is how data is presented to user.
*   In `MainMenu.xib` `PluginCellView` should have separate text fields for title, description and tags
*   Title, description and tag fields should be bound directly to model fields
*   Then we can bind text color to `PluginCellView` property so it can be changed when user select cell

Do you agree with this? If yes and if you want I can start working on this.

**Comment by xremix** [comment]
@nate-parrott this already changed, right? I think this issue can be closed.
