### ISSUE TITLE
Per-plugin options menu

### ISSUE THREAD

**Issue by hawkfalcon** [nate-parrott/Flashlight#23]
There are various ways you could solve some of the most common issues that have been brought up thus far. One potential solution is this: each plugin can have a options menu. This would be defined by the plugin. It could:
- toggle features on and off for one plugin
- choose what feature to use (e.g. the other issue regarding terminal vs iterm)

This could be implemented in many ways, even just include it in the existing json file.

This is just an idea, I think it would make Flashlight even better than it already is.

**Comment by nate-parrott** [comment]
@hawkfalcon @kanduvisla done! https://github.com/nate-parrott/Flashlight/wiki/Settings-API
