### ISSUE TITLE
Phrases for messages, reminders, mail, etc., are converted to lower case

### ISSUE THREAD

**Issue by toph-allen** [nate-parrott/Flashlight#238]
If I type, for instance, "message toph, What's up?", the resultant message is all in lower case. The same's true for the Reminders and Mail plug-ins.

![screen shot 2014-12-29 at 4 25 22 pm](https://cloud.githubusercontent.com/assets/3117884/5573241/b760d8f4-8f77-11e4-819e-4957d8f2e118.png)

 I'm not sure whether this is a decision on the part of the plug-in or the framework, but it would seem more in keeping with Apple's style to auto-sentence case things, or at the very least to let the user's capitalization stick.

**Comment by nate-parrott** [comment]
This should be fixed in the [latest release](https://github.com/nate-parrott/Flashlight/releases/tag/v0.96).
 I'm holding off on pushing it out as an auto-update, because it's not heavily tested yet, but please try it out.

**Comment by toph-allen** [comment]
This is indeed fixed. Thanks so much!
