### ISSUE TITLE
Can't stop FlashlightSIMBLAgent

### ISSUE THREAD

**Issue by DanielBocksteger** [nate-parrott/Flashlight#253]
I'm trying to install Adobe CC Applications but it's asking me to stop FlashlightSIMBLAgent. If i use the Activitycenter to stop the task it's restarting directly.

How to close the task?

**Comment by nate-parrott** [comment]
Open the Flashlight app, turn off "Enable Spotlight Plugins".

**Comment by DanielBocksteger** [comment]
Worked, thanks @nate-parrott

**Comment by iKorich** [comment]
v0.98.1 there is no way to disable plugin on 10.10.3 (14D113c)

**Comment by nate-parrott** [comment]
The disable option has been moved to the `Flashlight` menu:

![screen shot 2015-03-30 at 1 05 49 pm](https://cloud.githubusercontent.com/assets/3059249/6901783/9280780c-d6dd-11e4-9af2-c85797e2213c.png)

**Comment by doot0** [comment]
I've uninstalled Flashlight but the service still persists. How do I fix this?

**Comment by Njordy** [comment]
This is really bad. Disabling, quitting — nothing worked. Service still shows in Activity Monitor. I had to uinstall it using cleaning app in order to get rid of this problem.

**Comment by doot0** [comment]
FYI @nate-parott this blocks Adobe CC 2015 edition from completing installation.

**Comment by doot0** [comment]
FYI @nate-parrott this blocks Adobe CC 2015 edition from completing installation.

**Comment by mkormendy** [comment]
I had no problems with this. I went to flashlight, and disabled it in the menu as shown in the picture above. Then I quit the flashlight app. Then I was able to install the Adobe CC updates.
Once done, I loaded flashlight back up, and enabled it.

**Comment by tubook** [comment]
thanks @nate-parrott
