### ISSUE TITLE
Searching Apple's Developer Library

### ISSUE THREAD

**Issue by anoadragon453** [nate-parrott/Flashlight#255]
It would be useful to be able to search Apple's [Developer Library](https://developer.apple.com/library/ios/navigation/) using spotlight. They have a search system, though it isn't done through HTML headers.

Is this possible?

**Comment by nate-parrott** [comment]
There's a [dash search plugin](http://flashlight.nateparrott.com/plugin/dash), which searches using the [Dash](http://kapeli.com/dash) app — there's a bit of setup, but it works great.

Alternatively, someone could create a plugin to search their docs on the web, or the local docs that you download to your machine using Xcode.
