### ISSUE TITLE
Can't build from repo: PBXCp error with FlashlightKit.framework when building SpotlightSIMBL

### ISSUE THREAD

**Issue by shatteringlass** [nate-parrott/Flashlight#261]
I don't have much to start with: only this strange error, which claims   

>"error: /Users/Library/Developer/Xcode/DerivedData/Flashlight-ecbbmgoifutwxzgzjgruzjyizltl/Build/Products/Debug/FlashlightKit.framework: No such file or directory"

which of course is true, because it should be at least looking in /Users/*\<User\>*/Library/*etc*  

```
PBXCp /Users/Library/Developer/Xcode/DerivedData/Flashlight-ecbbmgoifutwxzgzjgruzjyizltl/Build/Products/Debug/FlashlightKit.framework /Users/federico/Library/Developer/Xcode/DerivedData/Flashlight-chyxxuwisrcqnlaxvqcdjzqcnhdj/Build/Products/Debug/SpotlightSIMBL.bundle/Contents/Frameworks/FlashlightKit.framework
    cd /Users/federico/repos/flashlight/FlashlightApp/SpotlightSIMBL
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -resolve-src-symlinks /Users/Library/Developer/Xcode/DerivedData/Flashlight-ecbbmgoifutwxzgzjgruzjyizltl/Build/Products/Debug/FlashlightKit.framework /Users/federico/Library/Developer/Xcode/DerivedData/Flashlight-chyxxuwisrcqnlaxvqcdjzqcnhdj/Build/Products/Debug/SpotlightSIMBL.bundle/Contents/Frameworks

error: /Users/Library/Developer/Xcode/DerivedData/Flashlight-ecbbmgoifutwxzgzjgruzjyizltl/Build/Products/Debug/FlashlightKit.framework: No such file or directory

```

**Comment by nate-parrott** [comment]
This is an issue I've had myself when building on another machine. I'll try to figure it out. (you can work around it by building the framework on its own and re-adding it to the `SpotlightSIMBL` target in various places — I don't have time to detail the exact process, so I'll just try to get it fixed)

**Comment by nate-parrott** [comment]
Is it working now? I've made some changes.

**Comment by shatteringlass** [comment]
10/10 can confirm building just fine
