### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by fuzzy76** [nate-parrott/Flashlight#267]
Since Flashlight does not notify the user of available updates until you manually start Flashlight.app, I am routinely several versions behind once I get the update dialog. But since the update dialog only shows the changes for the last version, I have no idea what changed in the versions between.

Could you atleast link up a full changelog somewhere? I guess you could use the full changelog instead of only the changes in the last version in the dialog.

**Comment by nate-parrott** [comment]
[Releases](https://github.com/nate-parrott/Flashlight/releases) contains the complete record of changes. That being said, it would definitely be nice to show a comprehensive list of all changes between your version and the most recent. The update system we're using (Sparkle) doesn't appear to have an easy way to do that though — maybe some day.
