### ISSUE TITLE
Latest Plugins / Updates

### ISSUE THREAD

**Issue by xremix** [nate-parrott/Flashlight#270]
I personally would be very interested in new or updated Plugins. What about displaying the 10 latest added or updated plugins in the Flashlight App?

**Comment by matth96** [comment]
+1

**Comment by nate-parrott** [comment]
that's a great idea. I'll give it a shot.

**Comment by nate-parrott** [comment]
done! (v0.96.4 is in Releases, should be pushed to auto-update soon)

**Comment by xremix** [comment]
nice!

**Comment by matth96** [comment]
nice, thank you!

**Comment by xremix** [comment]
I like how you solved that, thanks!
