### ISSUE TITLE
Localized search words not working anymore

### ISSUE THREAD

**Issue by xremix** [nate-parrott/Flashlight#279]
I figured out that only the english search file is working correctly. On a german environment I cannot search for "image duck", but not for "bild duck" what is the german translation.

**Comment by nate-parrott** [comment]
yep — I must have broken something recently. Just fixed it. Sorry about that :cry:

**Comment by xremix** [comment]
@nate-parrott Still having that problem. The translation of the plugin itself works perfectly, but the keywords do not. Currently I'm on 0.96.6.
No problem, I know you´re doing a great job!

**Comment by xremix** [comment]
@DanielBocksteger can you report the same?

**Comment by DanielBocksteger** [comment]
@xremix Ich versuche grad das nachzustellen, habe allerdings keinen Befehl 'image'... welche Plugin nutzt du für den test? Mir fällt gerade kein anderes ein.. aber etwas wie "herunterfahren" geht bei mir.

@ All: In english: I asked @xremix which Plugin he is using for this issue...

**Comment by xremix** [comment]
@DanielBocksteger Sehr merkwürdig. Bei mir funktioniert kein einziges Plugin in Deutsch und das auf zwei verschiedenen Computern. Ich werde versuchen herauszufinden woran das liegt.
