### ISSUE TITLE
Show Plugin Directory - in menu bar

### ISSUE THREAD

**Issue by xremix** [nate-parrott/Flashlight#280]
Having a menu item in the menu bar that opens the directory with the plugins in finder. Just small, but would save me some clicks. What do others think about this?

**Comment by nate-parrott** [comment]
@rogerskw, you mentioned you were working on something like this a while ago — any status update on that?

**Comment by rogerskw** [comment]
Still figuring it out. Work has been consuming a lot of my time lately though so not much progress.

What I have been trying to figure out is what process to attach the menu bar icon to. The SIMBL process seems to make more sense (versus the main app process) but I have had difficulty getting it to appear. If I attach it to the main process, it has to keep that extra process running unnecessarily when the SIMBL process is what actually matters.

**Comment by nate-parrott** [comment]
Yeah, attaching to the SIMBL process is definitely the way to go — esp. since it'll only be running when the Spotlight integration is running. not sure why it's difficult to get the menu extension to show up —let me know if you have questions I might be able to answer.

**Comment by nate-parrott** [comment]
Done!
