### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Aeonofgods** [nate-parrott/Flashlight#282]
Hey i just downloaded your program after someone on Reddit pointed it out to me. It seems awesome and so im pumped to try it.
I installed it and installed some plugins. However the plugins do not seem to be working in spotlight. Every time i open Flashlight it asks me to enable spotlight plugins, but it still does not work. I have uninstalled and installed it just to make sure. Im not sure what the issue is but if it helps im running the newest beta version of OS X Yosemite 10.10.2. Thanks!

**Comment by Mstormer** [comment]
Same issue here on Yosemite 10.10.1. I tried reinstalling and restarting, but nothing helps.

**Comment by nate-parrott** [comment]
Interesting... can you open up `console.app`, search "Flashlight," and attach the output?

**Comment by Mstormer** [comment]
1/19/15 11:20:24.101 PM Flashlight[706]: Sparkle: ===== Flashlight.app =====
1/19/15 11:20:41.290 PM Flashlight[706]: Sparkle: ===== Flashlight.app =====
1/19/15 11:21:53.648 PM Spotlight[71837]: #Flashlight SIMBLGot plugins: SpotlightSIMBL.bundle from /Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins
1/19/15 11:21:53.651 PM Spotlight[71837]: Hello from Flashlight! (/Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins/SpotlightSIMBL.bundle)
1/19/15 11:21:53.799 PM Spotlight[980]: #Flashlight SIMBLGot plugins: SpotlightSIMBL.bundle from /Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins
1/19/15 11:21:53.800 PM Spotlight[980]: Hello from Flashlight! (/Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins/SpotlightSIMBL.bundle)

**Comment by Aeonofgods** [comment]
Mine doesn't look quite as crazy as that i believe
1/19/15 9:57:31.715 PM Flashlight[22893]: DetectedSpotlightVersion: 916
1/19/15 10:10:02.383 PM Flashlight[22936]: DetectedSpotlightVersion: 916
1/19/15 10:10:05.487 PM Flashlight[22936]: Sparkle: ===== Flashlight =====
1/19/15 10:16:48.163 PM Flashlight[22954]: DetectedSpotlightVersion: 916
1/19/15 10:51:28.532 PM Flashlight[22954]: Sparkle: ===== Flashlight =====
1/19/15 10:53:04.943 PM Flashlight[23088]: DetectedSpotlightVersion: 916
1/19/15 11:02:42.974 PM Flashlight[23135]: DetectedSpotlightVersion: 916
1/19/15 11:03:29.115 PM Flashlight[23152]: DetectedSpotlightVersion: 916
1/19/15 11:03:35.405 PM Flashlight[23152]: INFO -- Moving myself to the Applications folder
1/19/15 11:03:36.747 PM Flashlight[23160]: DetectedSpotlightVersion: 916
1/19/15 11:03:45.863 PM Flashlight[23164]: DetectedSpotlightVersion: 916
1/20/15 7:14:45.728 AM Flashlight[23300]: DetectedSpotlightVersion: 916
1/20/15 7:16:42.226 AM Flashlight[23323]: DetectedSpotlightVersion: 916
1/20/15 7:17:55.578 AM Flashlight[23331]: DetectedSpotlightVersion: 916

**Comment by gnpappas** [comment]
1/20/15 6:31:33.061 AM Flashlight[8616]: DetectedSpotlightVersion: 916
1/20/15 6:31:38.763 AM com.nateparrott.Flashlight.FlashlightSIMBLAgent[8622]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
1/20/15 6:31:38.769 AM com.nateparrott.Flashlight.FlashlightSIMBLAgent[8622]: AppleEvents: Send port for process has no send right, port=( port:26507/0x678b rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
1/20/15 6:31:38.770 AM com.nateparrott.Flashlight.FlashlightSIMBLAgent[8622]: AppleEvents: Send port for process has no send right, port=( port:26507/0x678b rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
1/20/15 6:31:38.996 AM com.nateparrott.Flashlight.FlashlightSIMBLAgent[8622]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
1/20/15 6:31:38.996 AM com.nateparrott.Flashlight.FlashlightSIMBLAgent[8622]: AppleEvents: Send port for process has no send right, port=( port:26507/0x678b rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
1/20/15 6:31:38.997 AM com.nateparrott.Flashlight.FlashlightSIMBLAgent[8622]: AppleEvents: Send port for process has no send right, port=( port:26507/0x678b rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
1/20/15 6:31:39.062 AM Spotlight[8624]: #Flashlight SIMBLGot plugins: SpotlightSIMBL.bundle from /Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins
1/20/15 6:31:39.064 AM Spotlight[8624]: Hello from Flashlight! (/Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins/SpotlightSIMBL.bundle)
1/20/15 6:34:28.981 AM Flashlight[8663]: DetectedSpotlightVersion: 916
1/20/15 6:34:31.062 AM Flashlight[8663]: Sparkle: ===== Flashlight.app =====

**Comment by nate-parrott** [comment]
these are both pretty weird — I'm seeing "Hello from Flashlight!" in the logs, which indicates that Flashlight is starting correctly.

**Comment by Mstormer** [comment]
Yeah, mine started working today with the latest update, however it was launching fine when it was not working, it just wasn't modifying anything for spotlight.

**Comment by Aeonofgods** [comment]
I tried it again today and still could not figure out why it won't utilize any of the plugins or keep the "spotlight plugin" box checked

**Comment by nate-parrott** [comment]
What directory is the Flashlight app installed in?

**Comment by Aeonofgods** [comment]
It is installed in the application folder. However the "move myself to the applications folder" during installation moves it into my user/applications folder which is empty usually. However it works now after i have updated it
