### ISSUE TITLE
Add version number to about dialog

### ISSUE THREAD

**Issue by fuzzy76** [nate-parrott/Flashlight#284]
Your about dialog is missing (what I perceive to be) the most important part - a version number. :)

**Comment by nate-parrott** [comment]
Like this? :wink: (It was added in a very recent version.)
![screen shot 2015-01-20 at 12 47 45 pm](https://cloud.githubusercontent.com/assets/3059249/5822487/8f0de5ae-a0a2-11e4-9650-38385c4359d5.png)

**Comment by fuzzy76** [comment]
After installing an update today, I received it as well! :)
