### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by fuzzy76** [nate-parrott/Flashlight#285]
I am running 0.95.4

My Sparkle popup says "Flashlight 37 is now available - you have 0.95.4". As far as I can tell, there is no 37 release. And when I select to download and install, something is downloaded *and* extracted. I then press a button for "install and relaunch" and am told that an error occured when extracting the archive.

**Comment by fuzzy76** [comment]
```
20.01.15 10.35.49,275 Flashlight[2860]: Sparkle: ===== Flashlight.app =====
20.01.15 10.37.12,105 Flashlight[2860]: Sparkle: Extracting /Users/fuzzy76/Library/Application Support/Flashlight/.Sparkle/Flashlight 37/Flashlight.zip using 'ditto -x -k - "$DESTINATION"'
20.01.15 10.37.31,311 Flashlight[2860]: Sparkle: The host app is not signed using Apple Code Signing, and therefore cannot verify updates this way. Sparkle will use DSA signature instead.
20.01.15 10.37.31,312 Flashlight[2860]: Sparkle: The appcast item for the update has no DSA signature. The update will be rejected, because both DSA and Apple Code Signing verification failed.
20.01.15 10.37.35,101 Flashlight[2860]: Sparkle: Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed.
```

**Comment by nate-parrott** [comment]
Whoops! Somehow, I included the wrong cryptographic signature in the Appcast.xml feed the updater uses to find updates, so the updater refused to install the new version. Fixed now.

**Comment by fuzzy76** [comment]
Sorry, but it isn't. I am getting the same error.

**Comment by nate-parrott** [comment]
You're completely right — it's _finally_ fixed now. Thanks for the report!
