### ISSUE TITLE
Better Slack Integration

### ISSUE THREAD

**Issue by michaelhelmick** [nate-parrott/Flashlight#301]
I should have some time tomorrow to fix this. But I was excited to use the Slack integration only to find that it posted as `username (bot)`. This is because the plugin is using the Incoming Webhooks API. If it used the Slack Web API and asked for a user API Token in the Plugin Settings, and used the `im.open` and `im.close` API calls. It would be more useful. Right now direct messages go to the receiving users Slackbot channel, rather than their actual direct message thread.

`username_subtext` might be a nice addition too, the message would say "Mike Helmick via Flashlight", the subtext should be an optional setting, in my opinion.

**Comment by nate-parrott** [comment]
You should talk to @AlAdler about this — it's his plugin.

**Comment by michaelhelmick** [comment]
I managed to get it working using their Web API but it posts as a bot. I don't see why there isn't a way to just post as the user you're authenticated as. But I did get it to post to the right direct message thread. I'll try and send a PR tonight. 

—

**Comment by michaelhelmick** [comment]
Actually, they're adding the ability to post as the user that is authenticated. They just replied to a tweet. https://twitter.com/slackapi/status/560504375278178304

:cake:

**Comment by AlAdler** [comment]
It is pretty weird that they don't have this ability from the beginning. I hope they implement it soon.
