### ISSUE TITLE
Need OS X 10.10.2 support

### ISSUE THREAD

**Issue by ernestyao** [nate-parrott/Flashlight#306]
Won't work in OS X 10.10.2. Spotlight v917. An update needed.

**Comment by yaoxinghuo** [comment]
Works fine here. 10.10.2.

**Comment by klee-smartling** [comment]
Doesn't work here:

![flashlight-spotlight-error](https://cloud.githubusercontent.com/assets/10064899/5932186/16985cb4-a677-11e4-84b2-13deea8a2641.png)

**Comment by msxiao113** [comment]
10.10.2， doesn’t work at all

**Comment by xueye** [comment]
10.10.2, using flashlight 0.96.7 does not work.

**Comment by gboudreau** [comment]
![Error message](http://cl.ly/image/3Q2k2y3J2P2f/download/Image%202015-01-28%20at%2009%3A56%3A44.png)

**Comment by Gbear605** [comment]
0.96.8 is now available via auto-update. I'm pretty sure this is completely fixed now.

**Comment by nate-parrott** [comment]
It should be! (let me know if it isn't)
