### ISSUE TITLE
Plugin: Search Menu Bar

### ISSUE THREAD

**Issue by janniklorenz** [nate-parrott/Flashlight#354]
In Ubuntu 14.04 you can search the Menu Bar using the main search field. In OS X you can search it (in most Apps) using the Help section. It would be useful to search it directly in Spotlight.

Does anyone know how to access the Menu Bar Items or the Help search field in python?

**Comment by nate-parrott** [comment]
I wrote a pretty janky plugin that tries to accomplish this a while ago:

http://flashlight.nateparrott.com/plugin/click-menu

The biggest problem is that the only methods I know for accessing this data in Python (or at all) rely on Apple Events, which are pretty slow, especially when you're transferring a deep menu hierarchy between processes. (In addition, it doesn't seem to work in _all_ apps). 

If anyone knows of a better way to accomplish this, please reopen this issue.
