### ISSUE TITLE
I created an options and preferences file, but there is no settings button

### ISSUE THREAD

**Issue by FirePanther** [nate-parrott/Flashlight#379]
I created the both json files and even copied them from someone else (just to test), but the settings button will not appear in flashlight.
what else do I have to do to create the settings gui?
(I've read the guide on github)

thanks

![flashlight](https://cloud.githubusercontent.com/assets/1711106/6817634/e61f02e6-d2a3-11e4-90b7-d7a4c590fc25.jpg)

**Comment by nate-parrott** [comment]
Sorry about that!
Everything looks good to me.
Have you tried re-starting the Flashlight app?

(by the way, if you want to alter the appearance of your plugin when in Yosemite's dark mode, you can check for dark mode programmatically using the [dark mode module](https://github.com/nate-parrott/Flashlight/blob/master/UsefulModulesForPlugins/dark_mode.py), which you can copy into your project. If by "dark mode" you mean something else, never mind)

**Comment by FirePanther** [comment]
Thank you for this function :) I will implement it.
Yes, I restarted Flashlight, I had this problem for days and even restarted the Mac, there is something else wrong, but I have no idea what.
I think I have to check the Flashlight source to understand it. (btw. I just created the both files, didn't changed anything else)

**Comment by FirePanther** [comment]
ok i found the problem
the info.json "name" key wasnt EXACTLY the same like the (bundle-)foldername itself
thanks for your help and for flashlight! :+1: it replaced my alfred app :D
