### ISSUE TITLE
Slack plugin doesn't work with cyrillic letters

### ISSUE THREAD

**Issue by Igor10k** [nate-parrott/Flashlight#408]
When I try typing something like `slack #general привет` nothing happens.
Spotlight hides but message never shows up in Slack.

**Comment by nate-parrott** [comment]
@AlAdler made that plugin — any ideas?

**Comment by AlAdler** [comment]
Pull request #413 takes care of this.

**Comment by nate-parrott** [comment]
great, merged!

**Comment by Igor10k** [comment]
that was fast, thanks :)

**Comment by AlAdler** [comment]
пожалуйста
