### ISSUE TITLE
Reminder alarms

### ISSUE THREAD

**Issue by rstacruz** [nate-parrott/Flashlight#444]
The Remind Me plugin sets the due date for reminders, but doesn't set the "remind me on a day" alarm. This means you don't get the OSX notification when the actual time elapses.

that is, when I enter "remind me to gfto at 7pm", I'll get this:

![pasted_image_4_23_15__2_13_pm](https://cloud.githubusercontent.com/assets/74385/7291424/e71bdf80-e9c2-11e4-962a-22e03788b886.png)

but instead, I'm expecting this:

![pasted_image_4_23_15__2_13_pm](https://cloud.githubusercontent.com/assets/74385/7291422/e0112f92-e9c2-11e4-8234-b9af2aa2a230.png)

**Comment by nate-parrott** [comment]
fixed!
