### ISSUE TITLE
timezone plugin gives the wrong time

### ISSUE THREAD

**Issue by datacharmer** [nate-parrott/Flashlight#445]
The timezone piugin gives the wrong time for Helsinki, Vilnius, Athens, Bucharest, Kiev. These towns should have GMT+3, but the plugin shows UTC offset2, and the time is one hour behind.
![screenshot 2015-04-24 10 34 53](https://cloud.githubusercontent.com/assets/347371/7315524/8223b9b6-ea6e-11e4-815c-c13aa8203037.png)
![screenshot 2015-04-24 10 35 09](https://cloud.githubusercontent.com/assets/347371/7315525/822546f0-ea6e-11e4-9e12-14fc9925d20a.png)

**Comment by cHemingway** [comment]
This should now be fixed in Flashlight 1.0.1, with the pull request #454 above.

See this screenshot:
![screenshot 2015-05-06 01 21 29](https://cloud.githubusercontent.com/assets/3956920/7485475/39689c2c-f38e-11e4-8088-83392cf5ce46.png)

@nate-parrott, can you close this?

**Comment by datacharmer** [comment]
Thanks. Now it works as expected.

**Comment by cHemingway** [comment]
Excellent, could you close the issue?
