### ISSUE TITLE
Flashlight may have cache?

### ISSUE THREAD

**Issue by silentcarl** [nate-parrott/Flashlight#497]
I try to create the example "say" plug, when work is done, I typed "say something" on Flashlight, but there is no result, then I used FlashlightTool typed "say something", it worked well. and after a while, Flashlight could also be fine. 
Does anyone know the reason? 
osx: 10.10.3
Flashlight: 1.0.1

**Comment by cHemingway** [comment]
Hi, Flashlight itself doesn't reload plugins very often, to quote the [developer documentation](https://github.com/nate-parrott/Flashlight/wiki/Creating-a-Plugin#running-the-plugin) (emphasis mine):

>FlashlightTool automatically reloads plugin code pretty often, but **Flashlight itself is very conservative about reloading**. If things aren't working, try restarting Flashlight by toggling Enable Spotlight Plugins in the Flashlight window.

Does this answer your question?

**Comment by silentcarl** [comment]
it works well. thank you, @cHemingway
