### ISSUE TITLE
OSX Yosemite 10.10.4 Not working

### ISSUE THREAD

**Issue by FreedomCoder** [nate-parrott/Flashlight#527]
I just updated my laptop to 10.10.4 and Flashlight stopped working completely.

**Comment by jctull** [comment]
Same here. This is the console output relevant to Flashlight:

6/30/15 1:51:09.879 PM Flashlight[683]: DetectedSpotlightVersion: 917
6/30/15 1:51:10.396 PM Flashlight[683]: Sparkle: ===== Flashlight =====
6/30/15 2:47:57.230 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: SETTINGS CHANGED
6/30/15 2:47:57.433 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
6/30/15 2:47:57.444 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: AppleEvents: Send port for process has no send right, port=( port:30719/0x77ff rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
6/30/15 2:47:57.445 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: AppleEvents: Send port for process has no send right, port=( port:30719/0x77ff rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
6/30/15 2:47:57.624 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
6/30/15 2:47:57.624 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: AppleEvents: Send port for process has no send right, port=( port:30719/0x77ff rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
6/30/15 2:47:57.624 PM com.nateparrott.Flashlight.FlashlightSIMBLAgent[1434]: AppleEvents: Send port for process has no send right, port=( port:30719/0x77ff rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
6/30/15 2:48:16.163 PM Flashlight[1444]: DetectedSpotlightVersion: 917
6/30/15 2:48:19.932 PM Flashlight[1444]: Sparkle: ===== Flashlight =====

**Comment by matthewdias** [comment]
Today I found out how essential flashlight is to my workflow.

**Comment by tosslab-jay** [comment]
Please fix this!

**Comment by cHemingway** [comment]
This is a dupe of #494, see there for details.

**Comment by basnijholt** [comment]
Can confirm this

**Comment by puresick** [comment]
Same here!

**Comment by manuelrego27** [comment]
+1

**Comment by ppizarror** [comment]
same error

**Comment by issmirnov** [comment]
+1 
Anything we can do to help? Haven't looked at the code but seeing as this is pretty integral to my workflow would be happy to dive in and get it sorted.

**Comment by jk2K** [comment]
+1

**Comment by alanma** [comment]
Flashlight went dark after upgrading to OS X 10.10.4. 

Thanks for the great plugin. We'd appreciate if we could get Flashlight working again. 

Thanks!

**Comment by alby1481** [comment]
same here. no worky, worky.

**Comment by matthewdias** [comment]
It's obvious this is an issue. If people could stop commenting, it'd be great. The development work needs to be done upstream, so commenting here is not going to solve anything.

**Comment by basnijholt** [comment]
![np7fs](https://cloud.githubusercontent.com/assets/6897215/8480954/f97f9ef0-20e0-11e5-8f01-47ffd6760c99.jpg)

**Comment by FreedomCoder** [comment]
Closing this issue since it is a duplicate of #494.
