### ISSUE TITLE
It seemed not working on 10.10.4

### ISSUE THREAD

**Issue by cp0000** [nate-parrott/Flashlight#530]
I have installed the last release version, and can not using any of the plugins

**Comment by hakubo** [comment]
I have the same problem :(

**Comment by PeterAG** [comment]
I have the same.  Installed it and noticed that when i typed in the commands as shown in the demo nothing happened.  So I tried with and without quotation marks: nothing happens.  When I look in flashlight itself it shows all of the plugins are installed.  What to do?
