### ISSUE TITLE
Flashlight not working in 10.10.5 (14F6a)

### ISSUE THREAD

**Issue by asiSendGrid** [nate-parrott/Flashlight#539]
After upgrading to `10.10.5 (14F6a)` Flashlight stopped working. Please let me know if you need any system diagnostic/logs for further investigation.

**Comment by tsimmons** [comment]
Did you try [these instructions](https://gist.github.com/selaromi/59666a71387d39b5bfac) to get it to work? Because that's what it took to get it to work in 10.10.4.

**Comment by tsimmons** [comment]
@asiSendGrid So, did you try what I suggested?

**Comment by PixelPirate** [comment]
It worked for me on 10.10.5 👍🏻

**Comment by asiSendGrid** [comment]
@tsimmons didn't get a chance to try it, will give it a shot later this week. 

Cheers
