### ISSUE TITLE
Add custom search actions 

### ISSUE THREAD

**Issue by matth96** [nate-parrott/Flashlight#69]
With Alfred you could make custom searches. So I can search very fast on a website. For example: 
  
![schermafbeelding 2014-11-17 om 16 38 15](https://cloud.githubusercontent.com/assets/6486389/5076396/e27e7c42-6e9a-11e4-9985-d93efc43ada2.png)

**Comment by matude** [comment]
And this is the reason I just uninstalled Flashlight, trying to add a custom search plugin just took too much time/effort.

**Comment by nate-parrott** [comment]
You're right — I just made a plugin that lets you create custom search plugins: http://flashlight.nateparrott.com/plugin/custom-search
