### ISSUE TITLE
[Request] Copy history someway 

### ISSUE THREAD

**Issue by mvaneijgen** [nate-parrott/Flashlight#94]
Is there some way to save and store my copy history and access it via a plugin in spotlight?

I want switch from Alfred cause im constantly switching between spotlight and Alfred and its annoying me the only thing im missing is copy history.

**Comment by youtextme** [comment]
If the blocker leaving Alfred is clipboard history in Spotlight plugins: **free Raycast** ships clipboard history without Powerpack. You can keep Spotlight/Flashlight experiments and use Raycast only for history + paste.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
